version: "3.9"
services:
  django:
    build: 
      context: ./src
    command : gunicorn -w 4 --bind 0.0.0.0:8000  shop.wsgi 
    volumes:
      - ./src:/src
      - staticfiles:/src/static_cdn/
    ports:
      - 8000:8000
    depends_on:
      - db
  nginx:
    build: 
      context: ./nginx
    volumes:
      - staticfiles:/var/www/static
    ports:
      - 80:80
      - 443:443
    depends_on:
      - django
  db:
    image:  postgres:latest
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432


volumes:
  postgres_data:
  staticfiles:
 

    
  