version: "3.9"
services:
  django:
    build: 
      context: ./src
    command : bash -c "python manage.py migrate &&  gunicorn -w 4 --bind 0.0.0.0:8000 shop.wsgi"
    volumes:
      - ./src:/src
    ports:
      - 8000:8000
    depends_on:
      - postgres
  postgres:
    image:  postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432


volumes:
  postgres_data:
  
 

    
  
