version: "3.9"

services:
  django:
    build: 
      context: ./src
    command:
      - python mangage.py migrate 
      - gunicorn -w 4 --bind 0.0.0.0:8000  shop.wsgi 
    volumes:
      - ./src:/webapp
      - staticfiles:/webapp/static_cdn/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image:  postgres:latest
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
volumes:
  postgres_data:
  staticfiles:
 

    
  