# Generated by Django 4.2.2 on 2023-07-13 13:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=20)),
                ('title_en', models.CharField(max_length=20)),
                ('hex_code', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_brief', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('slug_url', models.SlugField()),
                ('category_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rootcategory', to='category.category')),
                ('category_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secound_category', to='category.category')),
                ('category_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_category', to='category.category')),
                ('category_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forth_category', to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVarient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_type', models.CharField(choices=[('color', 'رنگ'), ('size', 'اندازه'), ('width', 'ابعاد')], max_length=10)),
                ('weight', models.IntegerField(default=0, help_text='واحد به گرم میباشد')),
                ('dicount_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'بازه اعداد باید بالاتر صفر باشد '), django.core.validators.MaxValueValidator(100, 'تخفیف بالاتر از عدد 100 مجاز نیست ')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('color_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.color')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('size_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.size')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
