# Generated by Django 4.2.2 on 2023-07-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_title_remove_product_title_brief_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvarient',
            name='quantity',
            field=models.IntegerField(default=1, help_text='موجودیت'),
        ),
    ]
