# Generated by Django 4.2.2 on 2023-07-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug_url',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
