# Generated by Django 4.2.2 on 2023-07-16 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_slug_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug_url',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='color_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.color'),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='size_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.size'),
        ),
    ]
